# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/',
                'doc_host': '',
                'git_url': 'https://github.com/AnswerDotAI/basedpl',
                'lib_path': 'python/basedpl'},
  'syms': {}}
