"""Run the J language from Python and Jupyter through libj: sessions, magics and a Jupyter kernel.

`basedpl.j` runs the [J language](https://www.jsoftware.com/) inside the Python process. It loads libj, the engine library in every J installation, so no separate J process runs. The module provides the `J` session class, the `%%j` and `%j` magics, and a Jupyter kernel for J. Importing it does not start J.

Install J with `pip install jlanguage`, or from [jsoftware.com](https://www.jsoftware.com/). The Python layer needs `pip install 'basedpl[notebooks]'`.

Docs: https://answerdotai.github.io/basedpl/j.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/j.ipynb.

# %% auto #0
__all__ = ['find_j', 'J', 'JMagic', 'create_j_magic', 'load_ipython_extension', 'install_j_kernel', 'run_j_kernel', 'JError']

# %% ../../nbs/j.ipynb #9a091a86
import sys
from shutil import which
from fastcore.utils import *
from fastcore.xdg import xdg_config_home
from IPython.display import display
from ._core import _J, JError, _install_kernelspec, _run_j_kernel
from .notebooks import AplOut

_all_ = ['JError']

# %% ../../nbs/j.ipynb #728a92a9
_LIBJ = 'j.dll' if sys.platform=='win32' else 'libj.dylib' if sys.platform=='darwin' else 'libj.so'

def find_j():
    "Locate the J binary directory: the one containing libj and profile.ijs"
    if (p:=which('jconsole')) and (d:=Path(p).resolve().parent/_LIBJ).exists(): return d.parent
    try:
        import jlang
        return Path(jlang.path())/'bin'
    except ImportError: pass
    roots = [Path.home(), Path('/Applications'), Path('/opt'), Path('/usr/share')]
    cands = sorted(c for r in roots if r.exists() for c in r.glob('j9*') if (c/'bin'/_LIBJ).exists())
    if cands: return cands[-1]/'bin'
    raise FileNotFoundError('J not found: pip install jlanguage, or install it from jsoftware.com')

# %% ../../nbs/j.ipynb #c5bffe24
class J:
    "A J session: an engine from libj, with J's standard library loaded"
    def __init__(self, jbin=None): self._j = _J(Path(jbin or find_j())/_LIBJ)

# %% ../../nbs/j.ipynb #11f64311
@patch
def run(self:J, code):
    "Run `code` (one or more lines of J), returning its output; raises `JError` on J errors"
    return self._j.run(code)

@patch
def __call__(self:J, code):
    "Run `code`, returning displayable output, or None if there is none"
    return AplOut(self.run(code)) or None

# %% ../../nbs/j.ipynb #edd79864
def _nest(x, shape):
    "Nest flat sequence `x` (row-major ravel) into `shape`"
    if len(shape)<2: return x
    n = len(x)//shape[0]
    return [_nest(x[i*n:(i+1)*n], shape[1:]) for i in range(shape[0])]

@patch
def getm(self:J, name):
    "Read noun `name` into Python: str for characters; int/float scalars and (nested) lists otherwise"
    shape,x = self._j.get(name)
    return _nest(x, shape) if shape or isinstance(x,str) else x[0]

# %% ../../nbs/j.ipynb #d8c04417
@patch
def pyval(self:J, expr):
    "Evaluate `expr` and return the result as a Python value"
    self.run(f'pytmp =: {expr}')
    try: return self.getm('pytmp')
    finally: self.run("4!:55 <'pytmp'")

@patch
def __getitem__(self:J, expr): return self.pyval(expr)

# %% ../../nbs/j.ipynb #a010ad8f
def _flat(o): return [a for x in o for a in _flat(x)] if isinstance(o,(list,tuple)) else [o]

@patch
def __setitem__(self:J, nm, v):
    "Assign Python value `v` (scalar, string, or nested list) to noun `nm`"
    if isinstance(v,str): return self._j.set(nm, [len(v.encode())], v)
    shape,x = [],v
    while isinstance(x,(list,tuple)): shape,x = shape+[len(x)],x[0]
    self._j.set(nm, shape, _flat(v))

# %% ../../nbs/j.ipynb #b851b672
@patch
def fn(self:J, code):
    "A Python callable applying J verb `code` monadically or dyadically (left argument first)"
    def f(*args):
        if len(args)==1:
            self['pyy'] = args[0]
            return self.pyval(f'({code}) pyy')
        self['pyx'],self['pyy'] = args
        return self.pyval(f'pyx ({code}) pyy')
    return f

# %% ../../nbs/j.ipynb #0c583666
@patch
def interrupt(self:J):
    "Stop the running sentence with an attention interrupt; call it from another thread"
    self._j.interrupt()

# %% ../../nbs/j.ipynb #80c0283a
@patch
def close(self:J):
    "Free the engine; the session cannot run code afterwards"
    self._j = None

@patch
def __enter__(self:J): return self

@patch
def __exit__(self:J, *args): self.close()

# %% ../../nbs/j.ipynb #5037ca61
@patch(as_prop=True)
def exited(self:J):
    "The exit code requested by `exit`, or None"
    return self._j.exited

# %% ../../nbs/j.ipynb #39cbb993
class JMagic:
    "IPython `%j`/`%%j` magics, driving a lazily-started `J` session"
    def __init__(self, jbin=None): self.jbin,self.o = jbin,None

    def j(self, line, cell=None):
        "Run J: a cell magic displays the session output; a line magic returns the expression's Python value"
        if not self.o: self.o = J(self.jbin)
        if cell is None: return self.o[line.strip()]
        disp,cell = True,cell.rstrip()
        if cell.endswith(';'): disp,cell = False,cell[:-1]
        out = self.o(cell)
        if disp and out: display(out)

# %% ../../nbs/j.ipynb #d95a4701
def create_j_magic(shell=None):
    "Create a `JMagic` and register its `j` line/cell magic with `shell`, returning it"
    if not shell: shell = get_ipython()
    jm = JMagic()
    shell.register_magic_function(jm.j, 'line_cell', 'j')
    return jm

def load_ipython_extension(ipython):
    "Register the `j` magics: `%load_ext basedpl.j`"
    create_j_magic(shell=ipython)

# %% ../../nbs/j.ipynb #c76fabe6
def install_j_kernel(
    prefix=None, # Install under `prefix/share/jupyter/kernels` if given, else in the user Jupyter directory
):
    "Register the J kernel with Jupyter as kernelspec `j`, returning its directory"
    return _install_kernelspec('j', [sys.executable, '-m', 'basedpl.j', '{connection_file}'], 'J', 'J', prefix)

# %% ../../nbs/j.ipynb #2f155b38
def run_j_kernel(connection_file):
    "Serve a J kernel on the Jupyter connection in `connection_file`"
    startup = xdg_config_home()/'basedpl'/'startup.ijs'
    _run_j_kernel(connection_file, Path(find_j())/_LIBJ, startup.read_text() if startup.exists() else None)

# %% ../../nbs/j.ipynb #4e70e4af
if __name__ == '__main__':
    if sys.argv[1:] == ['install']: print(install_j_kernel())
    else: run_j_kernel(sys.argv[1])
