"""BPL magics and BPL output display for Jupyter and IPython

Docs: https://answerdotai.github.io/basedpl/magics.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/magics.ipynb.

# %% auto #0
__all__ = ['AplOut', 'display_event', 'BPLMagic', 'create_magic', 'load_ipython_extension', 'create_ipython_config']

# %% ../../nbs/magics.ipynb #fe6dcafd
import html, json, re, basedpl
from importlib.resources import files
from fastcore.utils import *
from . import symbols
from .ipython import load_ipython_extension as _load_help
from IPython.core.completer import context_matcher, SimpleCompletion
from IPython import get_ipython
from IPython.display import display, Javascript, HTML
from IPython.paths import get_ipython_dir


# %% ../../nbs/magics.ipynb #07eae6b5
class AplOut(str):
    "APL output text, displayed in the BPL code font where HTML is available."
    def __repr__(self): return str(self)
    def _repr_html_(self): return f'<pre class="bpl_out">{html.escape(self.rstrip(chr(10)))}</pre>'


# %% ../../nbs/magics.ipynb #3cdb5893
def display_event(e):
    "Display one output event, using its MIME bundle for a rich result. Text written with no line ending prints as it is."
    data = e['data']
    if e['kind'] == 'text': print(data['text/plain'], end='')
    elif set(data) == {'text/plain'}: display(AplOut(data['text/plain']))
    else: display(data, raw=True)

# %% ../../nbs/magics.ipynb #04f56c87
class BPLMagic:
    "IPython BPL magics that evaluate in the workspace `basedpl.bpl`."
    def __init__(self): self._loaded = False


# %% ../../nbs/magics.ipynb #940136d6
@patch
def _load(self:BPLMagic):
    if self._loaded: return
    js = files('basedpl')
    layout = (files('basedpl')/'layout.json').read_text()
    display(Javascript(f"{(js/'lb.js').read_text()}({json.dumps(symbols)}, {(js/'input.js').read_text()}, {layout})"))
    display(HTML(f"<style>{(js/'fonts.css').read_text()}</style>"))
    self._loaded = True

# %% ../../nbs/magics.ipynb #0b57e64c
@patch
def bpl(self:BPLMagic, line, cell=None):
    "Evaluate a line as a native value or display a cell as a BPL session."
    self._load()
    code = line if cell is None else cell.rstrip()
    show = not (cell is not None and code.endswith(';'))
    if not show: code = code[:-1]
    result = basedpl.bpl._eval(code, {}, display_event if show else None, echo=cell is not None)
    if cell is None: return result.value

# %% ../../nbs/magics.ipynb #18ff7023
@patch
@context_matcher(identifier='basedpl.names')
def complete(self:BPLMagic, context):
    "Complete visible BPL names in line and cell magics."
    empty = dict(completions=[])
    before = '\n'.join(context.full_text.split('\n')[:context.cursor_line] + [context.text_until_cursor])
    if m := re.match(r'%%bpl[^\S\n]*\n', before): code = before[m.end():]
    elif m := re.match(r'\s*(?:\w+\s*=\s*)?%bpl\s+', context.text_until_cursor): code = context.text_until_cursor[m.end():]
    else: return empty
    if any(m.end() == len(code) for m in re.finditer(r'''"(?:[^"]|"")*(?:"|$)|'(?:[^\n]'?|$)|⍝[^\n]*''', code)): return empty
    start = len(code)
    glyphs = {s['glyph'] for s in symbols} - {'•'}
    while start and code[start-1] not in glyphs and (code[start-1].isalnum() or code[start-1] in '_∆⍙•'): start -= 1
    prefix = code[start:]
    if not prefix: return empty
    return dict(completions=[SimpleCompletion(n, type='BPL name') for n in basedpl.bpl.complete(prefix)],
        matched_fragment=prefix, suppress=True)

# %% ../../nbs/magics.ipynb #953c6348
def create_magic(shell=None):
    "Register line and cell magics with `shell`. They evaluate in `basedpl.bpl`."
    if shell is None: shell = get_ipython()
    magic = BPLMagic()
    shell.register_magic_function(magic.bpl, 'line_cell', 'bpl')
    matchers = shell.Completer.custom_matchers
    matchers[:] = [m for m in matchers if getattr(m, 'matcher_identifier', None) != 'basedpl.names']
    matchers.append(magic.complete)
    _load_help(shell)
    return magic


# %% ../../nbs/magics.ipynb #3e0cb6bc
def load_ipython_extension(ipython):
    "Register the BPL magics when IPython loads this extension."
    create_magic(shell=ipython)

# %% ../../nbs/magics.ipynb #66869255
def create_ipython_config():
    "Called by `bpl-install-magic` to install magic"
    ipython_dir = Path(get_ipython_dir())
    cf = ipython_dir/'profile_default'/'ipython_config.py'
    cf.parent.mkdir(parents=True, exist_ok=True)
    if cf.exists() and 'basedpl.notebooks' in cf.read_text(): return print('BPL magics already installed!')
    with cf.open(mode='a') as f: f.write("\nc.InteractiveShellApp.extensions.append('basedpl.notebooks')\n\n")
    print(f"Jupyter config updated at {cf}")
