"""Generate native Windows keyboard tables from layout.json. Paths are relative to the repository root."""
import json
from pathlib import Path
from .keyboards import LAYOUT, write_changed

OUTPUT = Path('editors/windows/layout.h')
ROWS = [('1234567890-=', '!@#$%^&*()_+'), ('qwertyuiop[]', 'QWERTYUIOP{}'),
        (r"asdfghjkl;'`", r'ASDFGHJKL:"~'), (r'\zxcvbnm,./', '|ZXCVBNM<>?')]
OEM = dict(zip(r"-=[];'`\,./", ['MINUS', 'PLUS', '4', '6', '1', '7', '3', '5', 'COMMA', 'PERIOD', '2']))
CONTROL = {'[': '\x1b', ']': '\x1d', '\\': '\x1c', ' ': ' '}
SHIFT_CONTROL = {'2': '\x00', '6': '\x1e', '-': '\x1f'}


def keylayout(layout):
    "Generate Windows character and dead-key tables, using AltGr for Option."
    states = layout['states']

    def char(value):
        if value is None: return 'WCH_NONE'
        if isinstance(value, dict): return 'WCH_DEAD'
        return f'0x{ord(value):04x}'

    def row(vk, values, caps=0):
        return '    {' + f'{vk}, {caps}, ' + ', '.join(map(char, values)) + '},'

    lines = ['// Generated by basedpl.windows_keyboard from layout.json. Do not edit.',
             'static VK_TO_WCHARS6 characters[] = {']
    for plain, shifted in ROWS:
        for lo, hi in zip(plain, shifted):
            vk = f"'{lo.upper()}'" if lo.isalnum() else 'VK_OEM_' + OEM[lo]
            values = [lo, hi, CONTROL.get(lo), SHIFT_CONTROL.get(lo), layout['option'].get(lo), layout['option'].get(hi)]
            lines.append(row(vk, values, int(lo.isalpha())))
            if any(isinstance(v, dict) for v in values):
                lines.append(row('0xff', [states[v['state']]['terminator'] if isinstance(v, dict) else None for v in values]))
    for vk, lo, ctrl in [('SPACE', ' ', ' '), ('OEM_102', '\\', '\x1c'), ('DECIMAL', '.', None),
                         ('TAB', '\t', '\t'), ('BACK', '\b', '\x7f'), ('ESCAPE', '\x1b', '\x1b'),
                         ('RETURN', '\r', '\n'), ('CANCEL', '\x03', '\x03'),
                         ('ADD', '+', None), ('DIVIDE', '/', None), ('MULTIPLY', '*', None), ('SUBTRACT', '-', None)]:
        lines.append(row('VK_' + vk, [lo, '|' if vk == 'OEM_102' else lo, ctrl, None, None, None]))
    for digit in range(10): lines.append(row(f'VK_NUMPAD{digit}', [str(digit)] * 2 + [None] * 4))
    lines += ['    {0}', '};', '', 'static DEADKEY deadkeys[] = {']
    for state in dict.fromkeys(v['state'] for v in layout['option'].values() if isinstance(v, dict)):
        table = states[state]
        terminator = table['terminator']
        for key, value in (table['keys'] | {' ': terminator, terminator: terminator}).items():
            # A Windows dead-key result is one UTF-16 character; script minus and digit are typed separately.
            if isinstance(value, dict): value = states[value['state']]['terminator']
            lines.append(f'    DEADTRANS(0x{ord(key):04x}, 0x{ord(terminator):04x}, {char(value)}, 0),')
    return '\n'.join(lines + ['    {0}', '};', ''])


def write():
    "Write native Windows character and dead-key tables."
    write_changed(OUTPUT, keylayout(json.loads(LAYOUT.read_text())))
