"""Generate the US Windows keyboard from `layout.json`. Paths are relative to the repository root."""
import json
from pathlib import Path
from .keyboards import LAYOUT, write_changed

OUTPUT = Path('editors/windows/BasedPL-us.klc')
ROWS = [(0x02, '1234567890-=', '!@#$%^&*()_+'), (0x10, 'qwertyuiop[]', 'QWERTYUIOP{}'),
        (0x1e, r'''asdfghjkl;'`''', r'''ASDFGHJKL:"~'''), (0x2b, r'''\zxcvbnm,./''', '|ZXCVBNM<>?')]
OEM = dict(zip(r'''-=[];'`\,./''', ['MINUS', 'PLUS', '4', '6', '1', '7', '3', '5', 'COMMA', 'PERIOD', '2']))
CONTROL = {'[': '\x1b', ']': '\x1d', '\\': '\x1c', ' ': ' '}
SHIFT_CONTROL = {'2': '\x00', '6': '\x1e', '-': '\x1f'}


def keylayout(layout):
    "Generate MSKLC source, using AltGr for Option and separate keystrokes for script minus and digit."
    states = layout['states']

    def char(value):
        if value is None: return '-1'
        if isinstance(value, dict): return f'{ord(states[value["state"]]["terminator"]):04X}@'
        return f'{ord(value):04X}'

    lines = ['// Generated by basedpl.windows_keyboard from layout.json. Do not edit.',
             'KBD bplus "BasedPL-us"', 'COPYRIGHT "Answer.AI"', 'COMPANY "Answer.AI"', 'LOCALENAME "en-US"',
             'LOCALEID "00000409"', 'VERSION 1.0', '', 'SHIFTSTATE', '0', '1', '2', '3', '6', '7', '', 'LAYOUT']
    for start, plain, shifted in ROWS:
        for scan, (lo, hi) in enumerate(zip(plain, shifted), start):
            vk = lo.upper() if lo.isalnum() else 'OEM_' + OEM[lo]
            values = [lo, hi, CONTROL.get(lo), SHIFT_CONTROL.get(lo), layout['option'].get(lo), layout['option'].get(hi)]
            lines.append(f'{scan:02X}\t{vk}\t{int(lo.isalpha())}\t' + '\t'.join(map(char, values)))
    lines += ['39\tSPACE\t0\t0020\t0020\t0020\t-1\t-1\t-1',
              '56\tOEM_102\t0\t005C\t007C\t001C\t-1\t-1\t-1',
              '53\tDECIMAL\t0\t002E\t002E\t-1\t-1\t-1\t-1', '']
    for state in dict.fromkeys(v['state'] for v in layout['option'].values() if isinstance(v, dict)):
        table = states[state]
        terminator = table['terminator']
        keys = table['keys'] | {' ': terminator, terminator: terminator}
        lines.append(f'DEADKEY {ord(terminator):04X}')
        for key, value in keys.items():
            # Windows dead-key composition emits one UTF-16 character, never a string.
            if isinstance(value, dict): value = states[value['state']]['terminator']
            lines.append(f'{ord(key):04X}\t{char(value)}')
        lines.append('')
    lines += ['DESCRIPTIONS', '0409 BasedPL-us', '', 'LANGUAGENAMES', '0409 English (United States)', '', 'ENDKBD', '']
    return '\r\n'.join(lines)


def write():
    "Write the US Windows layout for Microsoft's Unicode keyboard compiler."
    write_changed(OUTPUT, keylayout(json.loads(LAYOUT.read_text())).encode('utf-16'))
