project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - href: getting-started.ipynb
        text: Get started
      - href: glyphs.qmd
        text: Glyph reference
      - href: python.ipynb
        text: Python
    right:
      - icon: github
        href: https://github.com/AnswerDotAI/basedpl
  sidebar:
    style: floating

execute:
  enabled: false

metadata-files: [nbdev.yml, sidebar.yml]
