//! Shared names for Python functions and glyph completion.
use std::{collections::HashMap, sync::OnceLock};

// One row per glyph: glyph, canonical name (docs/index.md), monad, dyad, extra completion aliases.
// Empty operation names mean that valence is not a primitive function; aliases are space-separated.
pub(crate) const SYMBOLS: &[(&str, &str, &str, &str, &str)] = &[
    ("←", "assign", "", "", "left-arrow"),
    ("→", "pipe", "", "", "right-arrow"),
    ("⍳", "iota", "iota", "index-of", ""),
    (":", "colon", "unkey", "keyed", ""),
    ("⍴", "rho", "shape", "reshape", ""),
    ("≢", "tally", "tally", "not-match", ""),
    ("≡", "match", "depth", "match", ""),
    ("+", "plus", "conjugate", "plus", ""),
    ("-", "minus", "negate", "subtract", ""),
    ("×", "times", "sign", "times", "multiply direction"),
    ("÷", "divide", "reciprocal", "divide", ""),
    ("⌈", "ceiling", "ceiling", "max", ""),
    ("⌊", "floor", "floor", "min", ""),
    ("|", "stile", "magnitude", "residue", "abs"),
    ("*", "star", "exponential", "exponent", "exp"),
    ("⍟", "log", "logarithm", "log", ""),
    ("○", "circle", "cis", "circle", ""),
    ("π", "pi", "pi-times", "pi-ratio", ""),
    ("√", "root", "sqrt", "root", ""),
    ("!", "factorial", "factorial", "binomial", ""),
    ("∧", "and", "polar", "lcm", ""),
    ("∨", "or", "real-imag", "gcd", ""),
    ("⍲", "nand", "square", "nand", ""),
    ("⍱", "nor", "double", "nor", ""),
    ("~", "tilde", "not", "without", ""),
    ("=", "equal", "classify", "equal", ""),
    ("≠", "not-equal", "unique-mask", "not-equal", ""),
    ("<", "less", "", "less", ""),
    ("≤", "less-or-equal", "decrement", "less-equal", ""),
    (">", "greater", "", "greater", ""),
    ("≥", "greater-or-equal", "increment", "greater-equal", ""),
    ("⎕", "quad", "", "", ""),
    ("•", "bullet", "", "", "system"),
    ("⍺", "alpha", "", "", ""),
    ("⍵", "omega", "", "", ""),
    ("⍶", "alpha-underbar", "", "", "left-operand"),
    ("⍹", "omega-underbar", "", "", "right-operand"),
    ("∇", "del", "", "", "recursion"),
    ("⍢", "del-diaeresis", "", "", "operator-recursion"),
    ("⍝", "comment", "", "", ""),
    ("⋄", "diamond", "", "", ""),
    ("¯", "overbar", "", "", ""),
    ("∞", "infinity", "", "", ""),
    ("⍬", "zilde", "", "", "empty"),
    (",", "comma", "ravel", "catenate", ""),
    ("⍪", "table", "table", "catenate-first", ""),
    ("⊂", "enclose", "enclose", "partitioned-enclose", ""),
    ("⊃", "mix", "mix", "pick", ""),
    ("⊆", "nest", "nest", "partition", ""),
    ("∊", "member", "enlist", "member", "epsilon"),
    ("∪", "union", "unique", "union", ""),
    ("∩", "intersection", "", "intersection", ""),
    ("⍋", "grade-up", "grade-up", "grade-up-by", ""),
    ("⍒", "grade-down", "grade-down", "grade-down-by", ""),
    ("↑", "take", "first", "take", "disclose"),
    ("↓", "drop", "split", "drop", ""),
    ("⌽", "reverse", "reverse", "rotate", ""),
    ("⊖", "reverse-first", "reverse-first", "rotate-first", ""),
    ("⍉", "transpose", "transpose", "reorder-axes", ""),
    ("⊤", "encode", "binary-encode", "encode", ""),
    ("⊥", "decode", "binary-decode", "decode", ""),
    ("⍎", "execute", "execute", "", ""),
    ("⍕", "format", "format", "format-spec", ""),
    ("⌷", "squad", "materialise", "index", ""),
    ("⌹", "domino", "inverse", "matrix-divide", ""),
    ("¨", "each", "", "", "dieresis"),
    ("/", "slash", "", "replicate", "reduce"),
    ("⌿", "slash-bar", "", "replicate-first", "reduce-first"),
    ("\\", "backslash", "", "expand", "scan"),
    ("⍀", "backslash-bar", "", "expand-first", "scan-first"),
    ("⍤", "rank", "", "", "atop"),
    ("∘", "compose", "", "", "jot bind"),
    ("⌝", "outer-product", "", "", ""),
    ("⍨", "commute", "", "", ""),
    ("⍥", "over", "", "", ""),
    ("⍛", "behind", "", "", ""),
    ("⍣", "power", "", "", "repeat iterate history"),
    ("⇄", "inverse-pair", "", "", ""),
    ("⌾", "under", "", "", ""),
    ("↕", "windows", "", "windows", ""),
    ("ℙ", "prime", "prime", "prime-mode", ""),
    ("⨸", "factor", "factors", "factor-spec", ""),
    ("⊛", "polynomial", "polynomial", "polyval", ""),
    ("∂", "derivative", "", "", ""),
    ("˘", "strand", "", "", "breve"),
    ("◶", "agenda", "", "", "choose"),
    ("⍸", "where", "where", "interval-index", ""),
    ("⍷", "find", "", "find", ""),
    ("⊢", "right", "same", "right", ""),
    ("⊣", "left", "same-left", "left", ""),
    ("⌸", "key", "", "", ""),
    ("@", "at", "", "", ""),
    ("⌺", "stencil", "", "", ""),
    ("?", "question", "roll", "deal", ""),
];

// Keys are US characters after Shift but before Alt. Browser adapters share this resource.
pub(crate) fn alt_keys() -> &'static HashMap<char, char> {
    static KEYS: OnceLock<HashMap<char, char>> = OnceLock::new();
    KEYS.get_or_init(|| serde_json::from_str(include_str!("../python/basedpl/keyboard.json")).expect("valid glyph keyboard"))
}

// The Alt chord's key on a US layout, shown beside each listed name: ` a`, or ` Sa` with Shift.
pub(crate) fn chord(glyph: &str) -> String {
    const SHIFTED: &str = "~!@#$%^&*()_+{}|:\"<>?";
    const PLAIN: &str = "`1234567890-=[]\\;',./";
    let Some((&key, _)) = alt_keys().iter().find(|&(_, &g)| glyph.chars().eq([g])) else { return String::new() };
    let base = SHIFTED.find(key).map_or(key.to_ascii_lowercase(), |i| PLAIN.as_bytes()[i] as char);
    format!(" {}{base}", if base == key { "" } else { "S" })
}
